[package]
name = "realms"
version = "0.1.0"
authors = ["alexandrejanin <alexandrejanin92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
noise = "0.6.0"
rand = "0.7.3"
rayon = "1.3.1"
